/**
 * Bundles the panel's browser code into the string the page, the fragment and `/client.js` serve.
 * Adapted from hackerpot.
 *
 * Why a build step at all: the client is real TypeScript modules under `src/client/`, which the
 * compiler checks, Biome lints and tests import; a library still needs to carry it as a string
 * it can serve from wherever it is mounted. The output is committed, so a fresh checkout can
 * serve a panel without a generate step. `--check` exits 1 when the committed copy no longer
 * matches its source, which is what CI runs first.
 *
 * Two bundles: the client, and its extras (charts and tables), which a panel that draws neither never
 * loads. See src/client/registry.ts. The main bundle must not contain the chart code; the build
 * checks that too, since one stray import would quietly undo the split.
 *
 * The build is also a lint gate. It refuses the sequences that would end or confuse the
 * `<script>` element the bundle is served in, and every way to put text into a document as
 * markup — naming the source file, so the fix starts in the right place.
 */
import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const entry = join(root, "src", "client", "index.ts");
const extrasEntry = join(root, "src", "client", "extras.ts");
const target = join(root, "src", "client.generated.ts");

const FORBIDDEN_IN_SCRIPT = ["</script", "<!--", "-->", "<script"];
const FORBIDDEN_SINKS = ["innerHTML", "outerHTML", "insertAdjacentHTML", "document.write", "eval(", "new Function"];

async function bundle(entryPoint) {
  const result = await build({
    entryPoints: [entryPoint],
    bundle: true,
    format: "iife",
    // Not minified: an operator's tool, where a hundred kilobytes costs nothing and being able to
    // read the running page in devtools does.
    minify: false,
    target: ["es2020"],
    platform: "browser",
    legalComments: "none",
    charset: "utf8",
    write: false,
    metafile: true,
    logLevel: "silent",
  });
  const code = result.outputFiles[0].text;
  await refuseSinks(code, result.metafile);
  return { code, inputs: Object.keys(result.metafile.inputs) };
}

async function refuseSinks(code, metafile) {
  const result = { metafile };
  const problems = [];
  for (const sequence of FORBIDDEN_IN_SCRIPT) {
    if (code.toLowerCase().includes(sequence)) problems.push(`contains ${JSON.stringify(sequence)}, which would end or confuse its <script> element`);
  }
  for (const sink of FORBIDDEN_SINKS) {
    if (!code.includes(sink)) continue;
    const sources = [];
    for (const input of Object.keys(result.metafile.inputs)) {
      const text = await readFile(join(root, input), "utf8").catch(() => "");
      if (text.includes(sink)) sources.push(relative(root, join(root, input)));
    }
    problems.push(`contains ${sink}${sources.length > 0 ? ` (in ${sources.join(", ")})` : ""}. Every value on the panel is text somebody else wrote, and reaches the document through textContent`);
  }
  if (problems.length > 0) throw new Error(`The panel client bundle ${problems.join("; and ")}.`);
}

export async function buildClient() {
  const main = await bundle(entry);
  const extras = await bundle(extrasEntry);
  const leaked = main.inputs.filter((input) => /src\/client\/(charts|table)\.ts$/.test(input));
  if (leaked.length > 0) throw new Error(`The main client bundle includes ${leaked.join(", ")}, which belong in the extras bundle only; import them through src/client/registry.ts.`);
  return `/**
 * Generated by \`node scripts/build-client.mjs\` from \`src/client/\`. Do not edit.
 *
 * The panel's browser code as strings: the client, served inline on the page and as \`/client.js\`
 * for an embedded fragment, and its extras (charts and tables), served only to panels that draw
 * them. See scripts/build-client.mjs for why this exists.
 */

export const CLIENT_SCRIPT = ${JSON.stringify(main.code)};

export const CLIENT_EXTRAS = ${JSON.stringify(extras.code)};
`;
}

const contents = await buildClient();
const existing = await readFile(target, "utf8").catch(() => "");
const name = relative(root, target);
if (process.argv.includes("--check")) {
  if (existing !== contents) {
    console.error(`${name} is out of date. Run \`node scripts/build-client.mjs\`.`);
    process.exit(1);
  }
  console.log(`${name} is up to date`);
} else if (existing === contents) {
  console.log(`${name} unchanged (${(contents.length / 1024).toFixed(1)} kB)`);
} else {
  await writeFile(target, contents);
  console.log(`${name} written (${(contents.length / 1024).toFixed(1)} kB)`);
}
